Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"

  config.vm.network :forwarded_port, guest: 80, host: 80, id:'http'
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh'

  config.vm.network "private_network", ip: "192.168.1.100"

  config.vm.synced_folder "./../app", "/var/www/akane.loc", group: 'www-data'
  config.vm.synced_folder "./provision", "/vagrant/provision", group: 'www-data'

  config.vm.provider "virtualbox" do |v|
    v.name  = "akane.loc"
    v.memory = 1000
    v.cpus = 1
  end
  config.vm.provision "shell", path: "./provision/provision.sh"
end
